### PR TITLE
Add discard operation

### LINKED ISSUE #86: Add discard operation
Some datasets contain unnecessary data, which is not useful in further processing. Why not to add option to remove those columns from dataset?

### PR DESCRIPTION
**Pull request by jan-swiatek**
Closes #86

Screenshot 2023-05-15 at 22 34 24

Screenshot 2023-05-15 at 22 35 02

### CODE REVIEW

**Comment by cristineguadelupe** [comment]
Hello @jan-swiatek! 
Thanks for the PR! Just a few minor tweaks:

- We need a more explicit label, something like `Columns to discard` instead of only `Columns`
- We use alphabetical order for the add operation buttons, so `Discard` should be first
- We avoid colors that might conflict with what we already use for warning and error messages in Livebook. Using red is not a problem, but it needs to be more faded and pastel (maybe light-crimson or pastel-crimson)

**Comment by jan-swiatek** [comment]
👋
Sure, I'll change that this afternoon then

**Comment by josevalim** [comment]
Hrm, I am wondering... instead of saying "Discard", maybe we should state the "positive". I.e. the goal is to "Select" which columns to show? Here is an idea:

1. We call the button "Select"
2. The label is called "Select columns"
3. By default, the input has all columns listed - you can click "x" to remove the ones you don't want

What do you think? Would that work?

**Comment by jan-swiatek** [comment]
> > Hrm, I am wondering... instead of saying "Discard", maybe we should state the "positive". I.e. the goal is to "Select" which columns to show? Here is an idea:
> > 
> > 1. We call the button "Select"
> > 2. The label is called "Select columns"
> > 3. By default, the input has all columns listed - you can click "x" to remove the ones you don't want
> > 
> > What do you think? Would that work?
> 
> I think it would be confusing because discarding columns is a common operation in the data cleaning process, and we usually have fewer columns to discard than to keep.

I agree. Both operations are possible with Explorer library, but usually only few columns are deleted and looking for them in select tag might be quite uncomfortable.

**Comment by josevalim** [comment]
> I agree. Both operations are possible with Explorer library, but usually only few columns are deleted and looking for them in select tag might be quite uncomfortable.

That's why I was thinking about listing all columns upfront, because then you only need to click on the ones you want to delete (no need to use the select input). So deletion is easier (there is no typing) and if you only want to keep certain ones, it should be possible too?

**Comment by josevalim** [comment]
When we emit the code, we can be smart. We can see how many columns we are keeping and how many we are removing and we emit the smallest code. So if we are keeping most columns, we use drop/discard, if we are deleting most, we keep select.

**Comment by josevalim** [comment]
Hi @jan-swiatek. I talked to @cristineguadelupe and we will go with her original proposal:

* We need a more explicit label, something like "Columns to discard"
* We use alphabetical order for the add operation buttons, so "+ Discard" should be first
* The colors need to be more faded and pastel (maybe light-crimson or pastel-crimson)

**Pull request merged**
